### ISSUE TITLE
Знаки препинания после кавычек

### ISSUE THREAD

**Issue by juunitaki** [akhx/typograf#10]
Версия: 0.1.0
### Текст
```text
"Привет", мир!
```

### Результат
```text
&laquo;Привет&raquo,&nbsp;мир!
```

### Желаемый результат
```text
&laquo;Привет&raquo;,&nbsp;мир!
```

### Описание ошибки
Правило Punctuation\DelDouble удаляет знаки препинания, не обращая внимания на html entities.
И ещё в нем ошибка:
public $name = 'Лишние знаки припинания';
- пр_е_пинания.

**Comment by akhx** [comment]
Спасибо за баг, поправил
