### ISSUE TITLE
Не ставится неразрывный пробел между инициалом и словом с большой буквы

### ISSUE THREAD

**Issue by arthurshlain** [akhx/typograf#14]
Версия: 0.4.10
### Текст
```text
балет им. П. И. Чайковского
```

### Результат
```text
балет им. П.[NBSP]И. Чайковского
```

### Желаемый результат
```text
балет им. П.[NBSP]И.[NBSP]Чайковского
```

### Возможное решение

```php
class AfterInitial extends AbstractRule
{

    public $name = 'Неразрывный пробел между инициалом и словом с большой буквы';

    public function handler(string $text): string
    {
        // Перед инициалом не должно быть других букв
        $before = '(?<!\p{L})';

        // Инициал с точкой, $1
        $initial = '(\p{Lu}\.)';

        // Слово с большой буквы, $2
        $word = '(\p{Lu}+)';

        $pattern = '#' . $before . $initial . '\s' . $word . '#iu';
        $replace = '$1' . $this->char['nbsp'] . '$2';

        return preg_replace($pattern, $replace, $text);
    }

}
```

А вот с сокращением «им.» (имени) не всё так просто, так как это может быть местоимением в конце предложения. 

Частичным решением может быть регулярка `(?<!\p{L})им\.\s(\p{Lu}\.)`, которая ищет инициал после сокращения «им.»:

![image](https://github.com/user-attachments/assets/398aa924-f6f1-4a35-a775-c29569437fd4)

**Comment by akhx** [comment]
Добрый день, спасибо за запрос.

Добавил правило расстановки неразрывных пробелов между инициалами и фамилией
