### ISSUE TITLE
Base64 для SafeBlock и другие правила

### ISSUE THREAD

**Issue by Tigla** [akhx/typograf#16]
Версия: 0.5.0

### Описание ошибки

Не совсем верно работает логика SafeBlock. 
В моем случаем к закодированному <head> base64 было применено правило [Number\DimensionSup](https://github.com/akhx/typograf/blob/master/src/Rule/Number/DimensionSup.php), в результате чего получаю такое:

<img width="877" alt="Screenshot 2024-09-03 at 21 13 10" src="https://github.com/user-attachments/assets/7b297fbc-f5ec-4a44-b7de-d3804781080f">

Как я понимаю было совпадение `m8`, в результате получаю замену на `m<sup>8</sup>` и вследствие чего base64 становится не валидным и обратно уже не может вернуть html код.

У себя как временное решение отключил правила для чисел:
```php
$typografed->disableRule('Number\*');
```

Видимо использование base64 не очень хорошее решение, или же в правилах сделать доп проверку что бы строка заменяемая не являлась base64.

**Comment by akhx** [comment]
Добрый день.
Переработал SafeBlock, убрал вообще base64, ибо с ним было много проблем, теперь блоки сохраняются в памяти, проблем должно стать меньше.

**Comment by Tigla** [comment]
Спасибо, как будет доступна новая версия в  composer - проверю.

**Comment by Tigla** [comment]
@akhx до сих пор не обновилась инфомарция о новой версии на packagist, v0.5.0 последняя версия числиться.

**Comment by akhx** [comment]
@Tigla вручную обновил, появился тег, проверю что с авто обновлением
