### ISSUE TITLE
Кавычки в шорткодах WordPress не должны заменяться

### ISSUE THREAD

**Issue by arthurshlain** [akhx/typograf#18]
Версия: 0.5.0
### Текст
```text
[gallery ids="100,101,102"]
```

### Результат
```text
[gallery ids="100,101,102″]
```

### Желаемый результат
```text
[gallery ids="100,101,102"]
```

**Comment by akhx** [comment]
Добрый день
Добавил конструкции [gallery] в safeBlock, я плохо знаком с шорткодами вордпреса, если там есть специфические коды которые могут повлиять на правила, прошу сообщить

**Comment by arthurshlain** [comment]
Шорткоды в WordPress могут быть как стандартные, так и произвольные. Произвольные шорткоды регистрирует сам разработчик сайта/темы/плагина WordPress.

Синтаксис шорткода:

```
[name]

[name /]

[name attribute="value" /]

[name attr1='value1' attr2="value2" ]

[name]Контент шорткода.[/name]

[name attr="value"]Контент шорткода.[/name]
```

Источник: https://wp-kama.ru/handbook/codex/shortcodes#sintaksis-shortkoda
