### ISSUE TITLE
Nbsp\BeforeShortLastWord и сокрашение

### ISSUE THREAD

**Issue by Tigla** [akhx/typograf#20]
Версия: 0.6.0

### Текст
```text
ул. Абрамцевская
```

### Результат
```text
nbsp;ул. Абрамцевская
```

### Желаемый результат
```text
ул. Абрамцевская
```

### Описание ошибки
В текущей версии правила "Nbsp\BeforeShortLastWord" не совсем корректно работает с сокрашениями адресов, особенно когда строка начинается именно с этого сокращения. В результате получаем вначале строки неразрывный пробел. Я думаю правильно сделать проверку, что бы это последнее слово не было так же и первым.

**Comment by akhx** [comment]
Приветствую @Tigla 
Можно полный текст, для полноты картины?

`Мальчик живёт на ул. Абрамцевская. Вот его дом.`

В таком тексте действительно пробел ставится некорректно перед `ул.` Правило считает что это заканчивается предложение и ставит пробел перед последним словом `ул`.

Как это решить пока не понятно, кроме как добавить слова исключения ул. влд. и т.д.

Но вы пишете про первое и последнее слово, не понимаю про что это, жду полный пример.

**Comment by Tigla** [comment]
@akhx день добрый.

В моем случаи это и есть конечная фраза. 
Можно сказать, вариант, когда эта сухая информация адреса, например заведения на странице контактов.

Кстати, с адресами еще было бы полезно ставить неразрывный пробел между сокращениями `д.`,  `стр.` и т.п.  и номером идущим следом.
Поэтому возможно наличие правила для работы с адресами было бы не лишним, где задать набор сокращений и исключений.

**Comment by akhx** [comment]
@Tigla Добавил новое правило для работы с адресами, должно помочь

**Comment by Tigla** [comment]
@akhx Благодарствую, теперь как нужно!
