### ISSUE TITLE
Ошибка в правиле Dash\IzZaPod

### ISSUE THREAD

**Issue by catsmeatman** [akhx/typograf#5]
Версия: 0.4.6

### Текст
```text
Карниз под покраску
```

### Результат
```text
Карниз-под покраску
```

### Желаемый результат
```text
Карниз под покраску
```

### Описание ошибки
Правило Dash\IzZaPod не учитывает, что "из" - может быть окончанием слова и в таких случаях не нужно ставить дефис.

**Comment by akhx** [comment]
Спасибо за баг

**Comment by catsmeatman** [comment]
Протестил. Всё ок.

Спасибо за оперативный фикс.
